### ISSUE TITLE
Add monitor groups to schema, database, api, front end

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-tokenomics#103]
Working on this already and pretty much have it solved -- but there's some stuff to talk about, and this will serve as a reminder :)

**Comment by tjayrush** [comment]
This is so specific, I am going to close it. It's talking about the issue of naming addresses. This has been fully worked out in the MVP which we should study so as to avoid a massive amount of duplication of effort.
