### ISSUE TITLE
Joint research with Ethereum Foundation

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-tokenomics#6]
Per [this doc](http://notes.eth.sg/s/rkxpeG0ff#3-ecosystem-analytics), Ethereum Foundation is offering funding/stipends for researchers working on "Ecosystem Analytics."

Some example projects they're interested in are: 

> 
> - Create analytics to add to platforms like ethstats.net. Particularly network-level measures quantifying decentralization, resistance to different attacks, etc.
> - “Econophysics” analyses of the ethereum economic ecosystem. Probably using data from etherscan.io.
> - Data-science analyses. E.g., how much Ether is unspendable, how often does Ether change hands, etc.

**Comment by tjayrush** [comment]
Absolutely!  Let's pursue this. Let's get http://tokenomics.io (or at least a starting point) up first. Then we can use that in our application. I'm 100% behind this idea.
